# Generated by Django 4.0.6 on 2022-07-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_Portal', '0005_alter_news_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
